@startuml Timing_Commande

title Timing Diagram - Timeline d'une Commande Type

concise "Marc\n(Chef Chantier)" as Marc
robust "Sylvie\n(Achats)" as Sylvie
robust "Éric\n(Dépôt)" as Eric
binary "Chantier" as Chantier

' Jour 1 - Lundi
@0
Marc is Besoin
Sylvie is Disponible
Eric is Attente
Chantier is 1

@5
Marc is ChercheDoc

@10
Marc is RemplitBon

@15
Marc is AppelSylvie
Sylvie is Reunion

@40
Marc is Attend

@45
Marc is AppelSylvie
Sylvie is TraiteAppel

@50
Marc is Attend
Sylvie is ChercheSage

@62
Sylvie is ChercheExcel

@70
Sylvie is AppelFourn

@85
Sylvie is EmailConfirm

@95
Sylvie is SaisieSage

@100
Sylvie is SaisieExcel

@105
Sylvie is Disponible
Marc is Attend

@110
Chantier is 0

@1440
Marc is AppelSuivi
Sylvie is RenseigneMarc

@1455
Marc is Attend
Sylvie is Disponible

@2880
Eric is Reception

@2895
Eric is ChercheDoc

@2910
Eric is CompareRef

@2920
Eric is AppelSylvie
Sylvie is RenseigneEric

@2930
Eric is Compte
Sylvie is Disponible

@2940
Eric is Range

@2950
Eric is AttendPC

@2965
Eric is SaisieSage

@2985
Eric is Attente
Marc is RecupereDepot

@3000
Marc is RetourChantier

@3015
Marc is Deballage

@3020
Marc is ERREUR
Chantier is 0

@3025
Marc is AppelFurieux
Sylvie is GereErreur

@3040
Marc is Attend
Sylvie is Disponible
Eric is Attente

@enduml
