@startuml Gantt_Comparaison_Avant_Apres

title Comparaison Temps - Avant/Après (Prise de RDV)

@startgantt
printscale daily zoom 2

caption Système ACTUEL vs CIBLE - Prise de RDV Client

Project starts 2025-11-17

-- Système ACTUEL (48 heures) --
[Client appelle] lasts 5 minutes
[Client appelle] is colored in LightCoral

[Claire cherche infos] lasts 10 minutes
[Claire cherche infos] is colored in LightCoral

[Propose créneau incertain] lasts 5 minutes
[Propose créneau incertain] is colored in Orange

[Mail Gaëtan] lasts 5 minutes
[Mail Gaëtan] is colored in LightCoral

[ATTENTE Gaëtan] lasts 7 hours
[ATTENTE Gaëtan] is colored in Red

[Gaëtan répond] lasts 2 minutes
[Gaëtan répond] is colored in LightCoral

[Appel client (répondeur)] lasts 5 minutes
[Appel client (répondeur)] is colored in Orange

[Mail client] lasts 10 minutes
[Mail client] is colored in LightCoral

[ATTENTE client] lasts 15 hours
[ATTENTE client] is colored in Red

[Client répond OK] lasts 2 minutes
[Client répond OK] is colored in LightCoral

[Saisie Excel + Outlook] lasts 5 minutes
[Saisie Excel + Outlook] is colored in LightCoral

[Mails confirmation] lasts 10 minutes
[Mails confirmation] is colored in LightCoral

-- Système CIBLE (2 minutes) --
[Client sur portail] lasts 1 minute
[Client sur portail] is colored in LightGreen
[Client sur portail] starts 2025-11-17

[Choisit créneau dispo] lasts 30 seconds
[Choisit créneau dispo] is colored in LightGreen

[Confirmation automatique] lasts 30 seconds
[Confirmation automatique] is colored in LightGreen

@endgantt
@enduml
