@startmindmap Pain_Points_Service_Client

title Pain Points Service Client

* 🔴 SERVICE CLIENT
** Temps perdu
*** Prise RDV (10h/j)
*** Recherche info
*** Double saisie
*** Relances manuelles

** Opportunités perdues
*** Demandes techniciens
*** Clients SAV
*** Devis terrain
*** Refacturation heures
*** Clients oubliés (post-it)

** Clients perdus
*** Insatisfaction (rétention -10%)
*** Délais inacceptables
*** Oublis

left side

** Système post-it\n**🔴 Critique**
*** Aucune traçabilité\n(80% risque oubli)
*** Post-it perdu/jeté\n10 clients/an perdus

** Données éparpillées\n**🔴 Critique**
*** 7 outils (ERP, SAGE, Excel...)\nAucune intégration
*** Double/triple saisie\nIncohérences

** Planning RDV archaïque\n**🔴 Critique**
*** 48h pour RDV\nvs 2 min possible
*** Excel non sync\nGaëtan pas consulté

** CERFA papier\n**🟠 Important**
*** Chronophage (10 min/intervention)\n400h/an
*** Illisible\nPas pro

** Portail client inexistant\n**🟠 Important**
*** Appels entrants élevés\n-40% possible
*** Disponibilité 8h-18h\nvs 24/7

@endmindmap
