@startuml Gantt_Comparaison_Intervention

@startgantt

title Comparaison Temps Avant Apres Intervention SAV

printscale daily

Project starts 2025-11-17

[SYSTEME ACTUEL - 2h44] lasts 1 day and is colored in Red

[Preparation tournee] lasts 1 day and is colored in LightCoral and 

[Deplacement client] lasts 1 day and is colored in LightCoral and 

[Appel Clothilde infos] lasts 1 day and is colored in Orange and 

[Intervention technique] lasts 1 day and is colored in LightGreen and 

[CERFA papier remplir] lasts 1 day and is colored in Red and 

[Photos tel perso] lasts 1 day and is colored in Orange and 

[Signature papier] lasts 1 day and is colored in LightCoral and 

[Retour scan CERFA] lasts 1 day and is colored in Red and 

-- VERSUS --

[SYSTEME CIBLE - 1h58] lasts 1 day and is colored in LightGreen and 

[Preparation tournee C] lasts 1 day and is colored in LightGreen and 

[Deplacement optimise] lasts 1 day and is colored in LightGreen and 

[Intervention technique C] lasts 1 day and is colored in LightGreen and 

[Rapport digital app] lasts 1 day and is colored in LightGreen and 

@endgantt
@enduml
