@startmindmap Solutions_RH

title Mind Map - Solutions Cibles (Odoo + PayFit)

* SOLUTIONS CIBLES
** Paie\nAutomatisée
***_ Sync Auto Odoo > PayFit
***_ Plus de Ressaisies
***_ DSN Automatique
***_ Bulletins Justes

** Gestion\nQuotidienne
***_ App Mobile (Congés)
***_ Scan Notes de Frais
***_ Annuaire Entreprise
***_ Organigramme à jour

** Onboarding\nFluide
***_ Checklist Digitale
***_ Matériel Prêt J1
***_ Accès IT Auto
***_ Marque Employeur

left side

** Gain de\nTemps (Sophie)
***_ -2.5j / semaine
***_ Focus Humain
***_ Moins de Stress
***_ Plus de Valeur

** Conformité\n& Sécurité
***_ RGPD Respecté
***_ Historique Centralisé
***_ Coffre-fort Numérique
***_ Contrats à jour

@endmindmap
