@startuml Activity_Prise_RDV

title Processus Prise RDV Maintenance - ACTUEL vs CIBLE

partition "ACTUEL - Processus Manuel" #LightCoral {
  :Client souhaite RDV entretien;
  :Appelle Clothilde\n(8h-18h uniquement);
  :Clothilde decroche telephone;
  :Recherche client Excel (2 min);
  :Verifie contrat Word (2 min);
  :Consulte planning Outlook (3 min);

  if (Creneau dispo ?) then (oui)
    :Propose creneau;
  else (non)
    :Recherche autre creneau (5 min);
    :Propose;
  endif

  :Client accepte ou negocie;
  :Saisie Outlook (2 min);
  :Saisie Excel (1 min);
  :Saisie GAO (2 min);
  :Redaction email confirmation (5 min);
  :Client recoit email confirmation;

  note right
    **TEMPS TOTAL : 19 min**
    Client attend : 8 min
    Clothilde : 19 min
    Triple saisie
    Dispo 8h-18h
  end note
}

partition "CIBLE - Portail Client 24/7" #LightGreen {
  :Client se connecte portail web\n(20h30 - soir);
  :Selectionne Prendre RDV;
  :Calendrier affiche creneaux\ndispos zone geo;
  :Choisit creneau (2 clics);
  :Confirmation automatique;
  :Recoit email + SMS rappel J-2;
  :Clothilde recoit alerte Nouveau RDV;
  :Valide RDV (2 min);

  note right
    **TEMPS TOTAL : 3 min**
    Client : 1 min autonome
    Clothilde : 2 min validation
    Zero ressaisie
    Dispo 24/7
    **GAIN : 17min x 600 RDV**
    **= 170h/an = 8,500 EUR**
  end note
}

@enduml
