@startuml Activity_Prise_RDV

title Processus Prise RDV Maintenance - ACTUEL vs CIBLE

start

fork
  partition "ACTUEL - Manuel" #LightCoral {
    :Client souhaite RDV;
    :<color:red>Appelle Clothilde</color>\n(8h-18h uniquement);
    :<color:red>Clothilde decroche</color>;
    :<color:red>Recherche client Excel</color>\n(2 min);
    :<color:red>Verifie contrat Word</color>\n(2 min);
    :<color:red>Consulte planning Outlook</color>\n(3 min);

    if (Creneau dispo ?) then (oui)
      :<color:red>Propose creneau</color>;
    else (non)
      :<color:red>Recherche autre creneau</color>\n(5 min);
    endif

    :<color:red>Client accepte</color>;
    :<color:red>Saisie Outlook</color> (2 min);
    :<color:red>Saisie Excel</color> (1 min);
    :<color:red>Saisie GAO</color> (2 min);
    :<color:red>Email confirmation</color>\n(5 min);
    :<color:red>RDV confirme</color>;

    note left
      **ACTUEL: 19 min**
      Client attend: 8 min
      Clothilde: 19 min
      Triple saisie
      Dispo 8h-18h
    end note
  }
fork again
  partition "CIBLE - Digital 24/7" #LightGreen {
    :Client souhaite RDV;
    :<color:green>Se connecte portail web</color>\n(20h30 - soir);
    :<color:green>Selectionne Prendre RDV</color>;
    :<color:green>Calendrier affiche creneaux</color>\ndispos zone geo;
    :<color:green>Choisit creneau</color>\n(2 clics);
    :<color:green>Confirmation auto</color>;
    :<color:green>Email + SMS rappel J-2</color>;
    :<color:green>Clothilde recoit alerte</color>;
    :<color:green>Valide RDV</color> (2 min);
    :<color:green>RDV confirme</color>;

    note right
      **CIBLE: 3 min**
      Client: 1 min autonome
      Clothilde: 2 min validation
      Zero ressaisie
      Dispo 24/7
      **GAIN: 17min x 600 RDV**
      **= 170h/an = 8,500 EUR**
    end note
  }
end fork

stop

@enduml
